init:
  - git config --global core.autocrlf true

environment:
  global:
    GH_REF: github.com/kamranayub/kamranayub.github.io.git
    WYAM_VERSION: v0.17.0
  matrix:
    - nodejs_version: "6"

platform:
  - x64

cache:
  - C:/Users/appveyor/.nuget/packages -> package.json
  - node_modules -> package.json
  - node_cache -> package.json  

branches:
  only:
    - source

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - mkdir wyam
  - 7z x tools/Wyam-%WYAM_VERSION%.zip -owyam -r
  - npm install

build_script:
  - .\wyam\Wyam.exe -r Blog -t CleanBlog

test: off

on_success:
  - git rev-parse HEAD > _commit.txt
  - set /P CURRENT_COMMIT=< _commit.txt
  - git clone -b master "https://%GH_TOKEN%@%GH_REF%" _deploy  
  - cd _deploy
  - git rm -rf .
  - xcopy ..\output /e /y
  - git status
  - git config user.name "Appveyor"
  - git config user.email "appveyor@kamranicus.com"
  - git add -A
  - git commit --allow-empty -m "Deploying site for %CURRENT_COMMIT%"
  - git push origin master